# Generated by Django 5.1.3 on 2024-12-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
