# Generated by Django 5.1.3 on 2024-12-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_declaration_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(default='En attente', max_length=20),
        ),
    ]
