# Generated by Django 5.1.3 on 2024-12-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_fonction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonction',
            name='number_person',
            field=models.IntegerField(default=0),
        ),
    ]
