# Generated by Django 5.1.3 on 2024-12-21 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_fonction_number_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fonction',
            name='declaration',
        ),
    ]
