# Generated by Django 5.1.3 on 2024-12-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_fonction_declaration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fonction',
            name='number_person',
        ),
    ]
