# Generated by Django 5.1.5 on 2025-01-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('account_number', models.CharField(max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bank_logos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
