# Generated by Django 5.1.5 on 2025-02-01 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_bank_created_at_bank_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('devise', models.CharField(max_length=50)),
                ('numero_compte', models.CharField(max_length=50, unique=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='montant',
            new_name='montant_usd',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='statut',
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_gnf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='permis',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.customuser'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='banque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='app.bank'),
        ),
        migrations.AddField(
            model_name='facture',
            name='payeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.payeur'),
        ),
    ]
