# Generated by Django 5.1.5 on 2025-02-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_payeur_rename_montant_facture_montant_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payeur',
            name='pays',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
