# Generated by Django 5.1.5 on 2025-02-02 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_payeur_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fonction_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.fonction'),
        ),
    ]
