# Generated by Django 5.1.5 on 2025-02-06 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_item_fonction_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='declaration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.customuser'),
        ),
        migrations.AddField(
            model_name='facture',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.customuser'),
        ),
    ]
