# Generated by Django 5.1.5 on 2025-02-11 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_declaration_company_declaration_user_facture_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='fonction_key',
        ),
        migrations.AlterField(
            model_name='item',
            name='fonction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.fonction'),
        ),
    ]
