# Generated by Django 5.1.3 on 2025-02-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_item_fonction_key_alter_item_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='empreinte',
            field=models.ImageField(blank=True, null=True, upload_to='photo_user/'),
        ),
        migrations.AddField(
            model_name='item',
            name='recto',
            field=models.ImageField(blank=True, null=True, upload_to='photo_user/'),
        ),
        migrations.AddField(
            model_name='item',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='photo_user/'),
        ),
        migrations.AddField(
            model_name='item',
            name='verso',
            field=models.ImageField(blank=True, null=True, upload_to='photo_user/'),
        ),
    ]
