# Generated by Django 5.1.3 on 2025-02-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_item_fonction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='permis',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
