# Generated by Django 5.1.3 on 2025-02-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_facture_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.AddField(
            model_name='declaration',
            name='type',
            field=models.CharField(default='Nouvelle', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='identifier',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
