# Generated by Django 5.1.3 on 2025-02-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_item_type_declaration_type_item_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='nationalite',
            new_name='telephone',
        ),
    ]
