# Generated by Django 5.1.3 on 2025-02-21 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_cabinet_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='Region',
            field=models.CharField(default='Conakry', max_length=50),
        ),
        migrations.AddField(
            model_name='bank',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_admin', to='app.customuser'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='Region',
            field=models.CharField(default='Conakry', max_length=50),
        ),
    ]
