# Generated by Django 5.1.3 on 2025-02-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_bank_region_bank_address_bank_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='Region',
            field=models.CharField(default='Conakry', max_length=200),
        ),
        migrations.AlterField(
            model_name='bank',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='identifier',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='swift_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
