# Generated by Django 5.1.3 on 2025-02-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_bank_region_alter_bank_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(default='actif', max_length=20),
        ),
    ]
