version: '3'
services:
  app:
    build:
      args:
        VUE_APP_DEV_URL: http://localhost:8000/
      context: .
      dockerfile: prod.Dockerfile
    # command: ["npm", "run", "start"]
    volumes:
      - ./:/app          # Syncs local code with the container
      - /app/node_modules      
    networks:
      - vue-network
    ports:
      - "8080:3033"

networks:
  vue-network:
    driver: bridge
